### ISSUE TITLE
data and output standardization when using drugSensitivitySig()

### ISSUE THREAD

**Issue by MomenehForoutan** [bhklab/PharmacoGx#103]
Hello there,
The `drugSensitivitySig()` has an argument, called `standardize` (which can be one of the SD, rescale and none); the help page says "One of "SD", "rescale", or "none", for the **form of standardization of the data to use**. "; is that the drug response data (e.g. AAC) or the molecular data (e.g. transcriptomics) or both which are reformatted based on what we choose for this argument? 
Also, does the function standardize the beta estimates; if so, the interpretation of the values are not intuitive to me; for example, does a standardized estimate of 0.3 mean that the gene expression has positive associations with drug response? Is there a way for us to get the actual beta estimates rather than standardized version of them? 
If we want to subset to genes that have the highest association with drug response, would you recommend taking top X genes with  the highest absolute estimates? I realise that most genes would not have significant FDR if we test all genes together so perhaps using FDR is not the best way to subset to the important genes?
Many thanks!
Sepideh

**Comment by ChristopherEeles** [comment]
Hi @MomenehForoutan,

I will preface this by saying I am not the author of that specific function in the package. But I do maintain the code.

The standardization is actually done inside the `geneDrugSensitivity` function. Looking at the code it appears standardization is applied to both the molecular feature and the drug response variables in the generalized linear model.

As far as I know the beta values are not standardized and can be interpreted as such. Positive values indicate a positive relationship with the response variable (i.e., drug response) and negative the opposite. 

Standardization is done to learn the effect size of the drug response independent of the scale or units of the molecular feature or drug response metric. Predictions with these coefficients should apply the same standardization method to new molecular feature data you wish to make predictions for.

Regarding ranking results, I would filter by significance at some cut-off you decide is appropriate then, yes, order them by absolute value of the estimate. We always use FDR for filtering, since this will identify only the most robust gene drug associations.

If you want to do something different, use your best statistical judgement. Perhaps @p-smirnov has a more relevant opinion on this topic though?

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN

**Comment by MomenehForoutan** [comment]
Thank you for explaining this! This answered my question :-)
Cheers,
Sepideh
