### ISSUE TITLE
IC50 published vs recomputed

### ISSUE THREAD

**Issue by kris-nader** [bhklab/PharmacoGx#114]
Hi all! 

Thank you for a great resource! 

I was taking a look at your IC50 values and wondering if these are the absolute or relative IC50 values. I watched your workshop on discovering biomarkers(https://www.youtube.com/watch?v=i2_b6JeN6Vc) where you go over the drug sensitivity curve and I assume that when you say IC50-these would be the absolute IC50s but I just wanted to make sure. 

Also, I noticed that in the Psets, there are 2 values for ic50: published ic50 and recomputed ic50. I read "_Revisiting inconsistency in large pharmacogenomic studies”_  and I understand there is a very good correlation(between -logIC50recomputed and -logIC50published within a PSet) but I was just wondering what are the differences between the published and recomputed. 

Thank you so much for your help!
Kristen

**Comment by ChristopherEeles** [comment]
Hi @kris-nader,

 I was not familiar with the distinction between relative and absolute IC50 values, but based on [this article](https://www.graphpad.com/support/faq/relative-vs-absolute-ic50/) I am fairly confident we are reporting the relative IC50 values. Perhaps @p-smirnov can confirm this, as he is our resident expert on dose-response modelling.
 
Regarding the difference between the published and recomputed IC50 values, the published versions are those reported by the study author in the paper associated with a given data-set while the recomputed values were computed using `PharmacoGx`. For each dataset, we are interested in assessing the reproducibilty of the original study, which is why we include both values.

As you mentioned, the correlation is very good between the published and recomputed values, indicating that we were able to successfully reproduce their finding.

Best,
Christopher Eeles
Software Developer
Haibe-Kains Lab
PM-Research | UHN
