### ISSUE TITLE
GDSC1000: DrugSensitivitySig fails after SubsetTo

### ISSUE THREAD

**Issue by bhaibeka** [bhklab/PharmacoGx#15]
Example:

```
gdsc.pdacells <- rownames(cellInfo(GDSC1000))[!is.na(cellInfo(GDSC1000)[ , "tissueid"]) & cellInfo(GDSC1000)[ , "tissueid"] == "pancreas"]

gdsc.dn <- c("paclitaxel", "Trametinib", "Gemcitabine")

## subset the PSet
GDSC1000_PDAC <- PharmacoGx::subsetTo(GDSC1000, cells=gdsc.pdacells, drugs=gdsc.dn)
gdsc.genecor <- PharmacoGx::drugSensitivitySig(GDSC1000_PDAC, mDataType="rna", sensitivity.measure="auc_recomputed", drugs=gdsc.dn, nthread=nbcore)
```

It returns: Error in .validate_assayDataElementReplace(obj, value) : 
  object and replacement value have different dimensions

**Comment by bhaibeka** [comment]
It looks like the problem come from summarizeMolecularProfiles()
```
summarizeMolecularProfiles(GDSC1000_PDAC, mDataType="rna")
Error in .validate_assayDataElementReplace(obj, value) : 
  object and replacement value have different dimensions
```

**Comment by p-smirnov** [comment]
This is a known issue, caused by an update to Biobase that verifies the size of exprs.se matches size of exprs. 
Is this happening in the latest version of the package?





On Mon, Feb 13, 2017 at 5:35 PM -0500, "Benjamin Haibe-Kains" <notifications@github.com> wrote:












It looks like the problem come from summarizeMolecularProfiles()
summarizeMolecularProfiles(GDSC1000_PDAC, mDataType="rna")
Error in .validate_assayDataElementReplace(obj, value) : 
  object and replacement value have different dimensions

**Comment by bhaibeka** [comment]
I could not install it on Mordor because fgsea would not compile. I will try on my workstation tomorrow

**Comment by p-smirnov** [comment]
Weird, I don't remember adding fgsea as a dependency to PharmacoGx. The summarize function works properly in the newest version of PharmacoGx on Bioconductor, but Bioconductor version must be 3.4 to download updated PharmacoGx.
