### ISSUE TITLE
CTRP data set issue with latest PharmacoGx version (2.3.5)

### ISSUE THREAD

**Issue by hmkim** [bhklab/PharmacoGx#74]
HI!

I already downloaded the data set (CTRPv2.RData)

With opening this data, I can't call this in session perfectly.

![스크린샷 2020-12-15 오전 12 02 50](https://user-images.githubusercontent.com/4966343/102097723-9c516400-3e69-11eb-97af-f97b01340d29.png)

Could you check this, please?

**Comment by ChristopherEeles** [comment]
Hi @hmkim,

It seems the version of CTRPv2 you loaded uses the old PhamacoSet design, where molecular profiles are stored in Expression Sets instead of SummarizedExperiments.

You should be able to fix this by loading Biobase and SummarizedExperiment packages then running `molecularProfilesSlot(x) <- lapply(molecularProfilesSlot(x), as, 'SummarizedExperiment')`

Please let me know if this does not resolve your issue by sharing your sessionInfo.

Best,
Chris

**Comment by hmkim** [comment]
Hi, @ChristopherEeles 

Thank you! 

In your comment, this data provided by articles use the older version of Pharmacogenomics sets.
