### ISSUE TITLE
summarizeSensitivityProfiles not working after update

### ISSUE THREAD

**Issue by FarzanT** [bhklab/PharmacoGx#77]
Hello,
Going back to code I used a couple of months ago, I can see that PharmacoGx has now some dependency on CoreGx, and there seems to be an issue with "generics". Steps to reproduce:
```r
BiocManager::install("PharmacoGx")
require(PharmacoGx)
```
Had to change the following from "CTRPv2" to CTRPv2_2015, the former worked before.
```r
ctrp2 <- downloadPSet("CTRPv2_2015")

ctrp2_auc <- summarizeSensitivityProfiles(pSet = ctrp2, sensitivity.measure = "auc_recomputed", summary.stat = "median", fill.missing = T)
ctrp2_ic50 <- PharmacoGx::summarizeSensitivityProfiles(pSet = ctrp2, sensitivity.measure = "ic50_published", summary.stat = "median", fill.missing = T)
```
Both result in the following error:
```r
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘summarizeSensitivityProfiles’ for signature ‘"missing"’
```

Using R 4.0.3 on M1 Mac with macOS Big Sur 11.2.1
CoreGx version 1.2.0
PharmacoGx 2.2.3

**Comment by ChristopherEeles** [comment]
Hi @FarzanT,

All methods have been updated to be more generic after the release of `CoreGx`. This is because we now inherit from the `CoreSet` class in that package for `PharmacoGx`, `RadioGx` and `ToxicoGx`. 

As a result, the `pSet` argument is deprecated and should be replaced with `object`. You could also simply exclude the parameter name for the first argument (the PSet) and method dispatch will work as expected.

Please see `??summarizeSensitivityProfiles` for additional documentation on function usage.

So to fix your script:
```
ctrp2 <- downloadPSet("CTRPv2_2015")

ctrp2_auc <- summarizeSensitivityProfiles(object = ctrp2, sensitivity.measure = "auc_recomputed", summary.stat = "median", fill.missing = T)
ctrp2_ic50 <- PharmacoGx::summarizeSensitivityProfiles(object = ctrp2, sensitivity.measure = "ic50_published", summary.stat = "median", fill.missing = T
```

Let me know if this resolves your problem. 

Best,
Chris

**Comment by FarzanT** [comment]
Yes it did! Thanks for the explanation and the quick fix, much appreciated.
