### ISSUE TITLE
Where did the raw viability data for CCLE was retrieved and what normalization steps were performed on the raw viability values ?

### ISSUE THREAD

**Issue by Durdam** [bhklab/PharmacoGx#79]
I could not find the original source of the CCLE viability dataset. In the PharmacoSet data of CCLE when I retrieve the raw data from the R object using the below commad (just retrieved two examples)
> CCLEsmall@sensitivity[["raw"]][1:2,,]
, , Dose

                     doses1   doses2  doses3  doses4 doses5 doses6 doses7 doses8
drugid_AEW541_1321N1 "0.0025" "0.008" "0.025" "0.08" "0.25" "0.8"  "2.53" "8"   
drugid_AEW541_22Rv1  "0.0025" "0.008" "0.025" "0.08" "0.25" "0.8"  "2.53" "8"   

, , Viability

                     doses1   doses2  doses3   doses4   doses5 doses6 doses7 doses8
drugid_AEW541_1321N1 "108.67" "111"   "102.16" "100.27" "90"   "87"   "74"   "57"  
drugid_AEW541_22Rv1  "100.94" "112.5" "86"     "104.16" "75"   "68"   "48"   "29" 

Now, here the concentration data, I understand, it is provided on the CCLE website also and this is the file for that:

https://data.broadinstitute.org/ccle_legacy_data/pharmacological_profiling/CCLE_NP24.2009_Drug_data_2015.02.24.csv

But the Viability data, where is this coming from. There is no raw viability data available on CCLE website. Are these calculated using the 'Activity Data (Median)' and 'Activity SD' ? Kindly, shed light on this topic please or point me to the raw data source if any.

Thank you very much in advance.

**Comment by p-smirnov** [comment]
Hi @Durdam 

According to my notes, Activity Data (Median) is a % Response instead of a % viability. Therefore, we took 100 - Activity Data (Median) to recover the viability information. You can find our code here: https://github.com/BHKLAB-Pachyderm/downloadCCLESensRaw/blob/master/downloadSensData.R

We did not do any other processing or normalization on the values, as no more information was available until recently. The CCLE authors have published the raw measurement values in this addendum at the end of 2018: https://www.nature.com/articles/s41586-018-0722-x

**Comment by ChristopherEeles** [comment]
@Durdam,

We are closing this issue as it appears your question was answered. If this is not the case feel free to re-open the issue.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN
